# Generated by Django 5.0.3 on 2024-04-25 11:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Категория')),
                ('description', models.TextField(max_length=200, verbose_name='Описание категории')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('author', models.CharField(max_length=150, null=True, verbose_name='Автор')),
                ('publisher', models.CharField(max_length=150, null=True, verbose_name='Издательство')),
                ('isbn', models.CharField(max_length=100, null=True, verbose_name='ISBN')),
                ('year', models.IntegerField(null=True, verbose_name='Год')),
                ('number_of_pages', models.IntegerField(null=True, verbose_name='Количество страниц')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('book_theme', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('design', 'Дизайн'), ('gamedev', 'Gamedev'), ('analytics', 'Analytics'), ('ai', 'AI'), ('data', 'Data Science'), ('devops', 'DevOps'), ('qa', 'Quality Assurance'), ('CS', 'Computer Science'), ('OT', 'Other')], default='OT', max_length=30, verbose_name='Темы')),
                ('programming_language', models.CharField(choices=[('JavaScript', 'Javascript'), ('Java', 'Java'), ('Python', 'Python'), ('C#', 'Csharp'), ('C', 'Clanguage'), ('C++', 'Cplus'), ('SQL', 'Sql'), ('HTMLCSS', 'Htmlcss'), ('Ruby', 'Ruby'), ('PHP', 'Php'), ('TypeScript', 'Typescript'), ('Assembler', 'Assembler'), ('Bash/Powershell', 'Bash Powershell'), ('OT', 'Other')], default='OT', max_length=30, verbose_name='Язык программирования')),
                ('book_bindings', models.CharField(choices=[('Мягкий переплет', 'Softcover'), ('Твердый переплет', 'Hardcover')], default='Мягкий переплет', max_length=30, verbose_name='Переплёт')),
                ('translator_choice', models.CharField(choices=[('Имя переводчика', 'Translate'), ('Отсутствует', 'Notranslate')], default='Имя переводчика', max_length=30, verbose_name='Переводчик')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_value', models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Звезда рейтинга')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звёзды рейтинга',
                'db_table': 'rating_star',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Заголовок отзыва')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст отзыва')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='catalogue.products')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='catalogue.ratingstar', verbose_name='Звезда')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'review',
            },
        ),
    ]
