# Generated by Django 5.0.3 on 2024-03-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='book_type',
        ),
    ]
