# Generated by Django 5.0.3 on 2024-03-29 07:50

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_products_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='book_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('DE', 'Дизайн'), ('GD', 'Gamedev'), ('CS', 'Computer Science'), ('JS', 'JavaScript'), ('J', 'Java'), ('PY', 'Python'), ('C#', 'C#'), ('C', 'C'), ('C++', 'C++'), ('SQL', 'SQL'), ('OT', 'Другое')], default='FE', max_length=20, verbose_name='Темы'),
        ),
    ]
