# Generated by Django 5.0.3 on 2024-03-29 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_products_translator_choice_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_value', models.IntegerField(choices=[(1, 'Star1'), (2, 'Star2'), (3, 'Star3'), (4, 'Star4'), (5, 'Star5')], default=3, verbose_name='Значение рейтинга')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звёзды рейтинга',
                'db_table': 'rating_star',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='catalogue.products'),
        ),
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='catalogue.ratingstar', verbose_name='Звезда'),
            preserve_default=False,
        ),
    ]
