# Generated by Django 5.0.3 on 2024-03-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_ratingstar_alter_review_product_review_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='star_value',
            field=models.SmallIntegerField(default=0, verbose_name='Звезда рейтинга'),
        ),
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='catalogue.ratingstar', verbose_name='Звезда'),
        ),
    ]
