# Generated by Django 5.0.3 on 2024-04-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_ratingstar_star_value_alter_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(default='Описание', max_length=200, verbose_name='Описание категории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.categories', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratingstar',
            name='star_value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Звезда рейтинга'),
        ),
    ]
