# Generated by Django 5.0.3 on 2024-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_alter_products_theme_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='book_format',
            field=models.CharField(choices=[('paper', 'Бумажная'), ('online', 'Электронная')], default='online', max_length=30, verbose_name='Формат книги'),
        ),
        migrations.AddField(
            model_name='products',
            name='book_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('es', 'Spanish'), ('fr', 'French'), ('zh', 'Chinese'), ('de', 'German'), ('ja', 'Japanese')], default='en', max_length=30, verbose_name='Язык книги'),
        ),
    ]
