# Generated by Django 5.0.3 on 2024-04-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_categories_description_products_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
