# Generated by Django 5.0.3 on 2024-04-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_remove_products_book_type_products_book_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='book_theme',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('design', 'Дизайн'), ('gamedev', 'Gamedev'), ('analytics', 'Analytics'), ('ai', 'AI'), ('data', 'Data Science'), ('devops', 'DevOps'), ('qa', 'Quality Assurance'), ('CS', 'Computer Science'), ('OT', 'Other')], default='OT', max_length=30, verbose_name='Темы'),
        ),
    ]
