# Generated by Django 5.0.3 on 2024-04-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_products_book_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='programming_language',
            field=models.CharField(choices=[('JavaScript', 'Javascript'), ('Java', 'Java'), ('Python', 'Python'), ('C#', 'Csharp'), ('C', 'Clanguage'), ('C++', 'Cplus'), ('SQL', 'Sql'), ('OT', 'Other')], default='OT', max_length=30, verbose_name='Язык программирования'),
        ),
    ]
