# Generated by Django 5.0.3 on 2024-04-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_remove_products_category_products_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='level',
            field=models.IntegerField(default=1, max_length=2, verbose_name='Уровень книги'),
        ),
    ]
