# Generated by Django 5.0.3 on 2024-04-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_products_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень книги'),
        ),
    ]
