# Generated by Django 5.0.3 on 2024-06-02 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_count', models.IntegerField(verbose_name='Кол-во объектов')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='Текст вопроса')),
                ('question_type', models.TextField(choices=[('Theme Question', 'Theme'), ('Level Question', 'Level'), ('Language Question', 'Language'), ('Price Question', 'Price'), ('Programmed Before', 'Prog Before'), ('Programming Language Question', 'Prog Lang'), ('Theme Specific Question', 'Theme Specific'), ('Specific Level Question', 'Level Specific'), ('Theme for Other', 'Theme For Other'), ('Other General', 'Other Gen')], default='Theme Question', verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название теста')),
                ('quiz_theme', models.CharField(max_length=120, verbose_name='Тема теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=120, verbose_name='Текст ответа')),
                ('answer_value', models.TextField(verbose_name='Значение вопроса')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='quiz.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answer',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question', to='quiz.quiz', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(verbose_name='Тема')),
                ('level', models.TextField(verbose_name='Уровень знаний')),
                ('language', models.TextField(verbose_name='Язык')),
                ('price', models.TextField(verbose_name='Цена')),
                ('programmed_before', models.TextField(verbose_name='Программировал ранее')),
                ('prog_lang', models.TextField(verbose_name='Язык программирования')),
                ('theme_specific', models.TextField(verbose_name='Подтема')),
                ('level_specific', models.TextField(verbose_name='Уровень(для категории)')),
                ('theme_other', models.TextField(blank=True, null=True, verbose_name='Тема(другое)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result', to='quiz.quiz', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150, verbose_name='Заголовок')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='quiz.result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_level', models.IntegerField(verbose_name='Уровень узла')),
                ('product', models.ManyToManyField(related_name='roadmap_book', to='catalogue.products')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='quiz.roadmap')),
            ],
            options={
                'ordering': ['node_level', 'pk'],
            },
        ),
    ]
