# Generated by Django 5.0.3 on 2024-04-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='Текст вопроса')),
                ('question_type', models.TextField(choices=[('Theme Question', 'Theme'), ('Level Question', 'Level'), ('Language Question', 'Language'), ('Price Question', 'Price'), ('Programmed Before', 'Prog Before'), ('Programming Language Question', 'Prog Lang'), ('Other', 'Other')], default='Theme Question', verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название теста')),
                ('quiz_theme', models.CharField(max_length=120, verbose_name='Тема теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'quiz',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=120, verbose_name='Текст ответа')),
                ('answer_value', models.TextField(verbose_name='Значение вопроса')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='quiz.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answer',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question', to='quiz.quiz', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(verbose_name='Тема')),
                ('level', models.TextField(verbose_name='Уровень знаний')),
                ('language', models.TextField(verbose_name='Язык')),
                ('price', models.TextField(verbose_name='Цена')),
                ('programmed_before', models.TextField(verbose_name='Программировал ранее')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result', to='quiz.quiz', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'db_table': 'result',
            },
        ),
    ]
