# Generated by Django 5.0.3 on 2024-04-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_value',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Master')], default=1, verbose_name='Значение вопроса'),
        ),
    ]
