# Generated by Django 5.0.3 on 2024-06-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='specific_question_type',
            field=models.TextField(choices=[('FE', 'Fe'), ('BE', 'Be'), ('DES', 'Des'), ('DO', 'Do'), ('DS', 'Ds'), ('GD', 'Gd'), ('AN', 'An'), ('AI', 'Ai'), ('TEST', 'Test'), ('CS', 'Cs'), ('Other', 'Other'), ('All', 'All')], default='All'),
        ),
    ]
