# Generated by Django 5.0.3 on 2024-04-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_answer_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_value',
            field=models.IntegerField(verbose_name='Значение вопроса'),
        ),
    ]
