# Generated by Django 5.0 on 2024-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_specific_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='specific_question_type',
            field=models.TextField(choices=[('frontend', 'Fe'), ('backend', 'Be'), ('design', 'Des'), ('devops', 'Do'), ('data', 'Ds'), ('gamedev', 'Gd'), ('analytics', 'An'), ('ai', 'Ai'), ('qa', 'Test'), ('CS', 'Cs'), ('OT', 'Other'), ('all', 'All')], default='all'),
        ),
    ]
