# Generated by Django 5.0.3 on 2024-04-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_answer_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.TextField(choices=[('Theme Question', 'Theme'), ('Level Question', 'Level'), ('Purpose Question', 'Purpose'), ('Language Question', 'Language'), ('Price Question', 'Price')], default='Theme Question', verbose_name='Тип вопроса'),
        ),
    ]
