# Generated by Django 5.0.3 on 2024-04-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_result_theme_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapnode',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='node', to='quiz.roadmap'),
        ),
    ]
