# Generated by Django 5.0.3 on 2024-04-13 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz.quiz', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='AnswerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=120, verbose_name='Текст ответа')),
                ('answer_low', models.IntegerField(null=True, verbose_name='Нижнее значение цены')),
                ('answer_high', models.IntegerField(null=True, verbose_name='Верхнее значение цены')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_price', to='quiz.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ цены',
                'verbose_name_plural': 'Ответы цены',
                'db_table': 'answer_price',
            },
        ),
    ]
