# Generated by Django 5.0.3 on 2024-05-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_result_theme_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_count', models.IntegerField(verbose_name='Кол-во объектов')),
            ],
        ),
    ]
