# Generated by Django 5.0.3 on 2024-05-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_objectcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapnode',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='quiz.roadmap'),
        ),
    ]
