# Generated by Django 5.0.3 on 2024-05-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pick_up_point',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Пункт выдачи'),
        ),
    ]
