# Generated by Django 5.0.3 on 2024-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_pick_up_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='author',
            field=models.CharField(default='Author test', max_length=150, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
