# Generated by Django 5.0 on 2024-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='В ожидании заполнения', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
