# Generated by Django 5.0.3 on 2024-04-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.TextField(max_length=50, null=True, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.TextField(max_length=10, null=True, verbose_name='Номер телефона'),
        ),
    ]
