# Generated by Django 5.0.3 on 2024-05-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_user_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.TextField(max_length=15, null=True, verbose_name='Номер телефона'),
        ),
    ]
